/* Problem 12: Highly Divisible Triangluar Number
The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:
 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28

We can see that 28 is the first triangle number to have over five divisors.
What is the value of the first triangle number to have over five hundred divisors?
*/

import java.io.*;
import java.util.*;
import java.lang.Math.*;

public class Problem12 {
	public static void main(String[] args) {
		long startTime = System.currentTimeMillis();
		
		int triangle = 0;
		int i = 1;

		while (numberOfDivisors(triangle) < 500) {
			System.out.printf("%s\t%d\t%s\t%d","Triangle:",triangle,"Num Divisors:",numberOfDivisors(triangle));
			System.out.println();
			triangle += i;
			i++;
		}

		System.out.println(triangle);

		long endTime = System.currentTimeMillis();
		long totalTime = endTime - startTime;
		System.out.println("Total run time was " + totalTime + " milliseconds.");
	}

	private static int numberOfDivisors(int number) {
		int divisors = 0;
		int sqrt = (int)Math.sqrt(number);

		for (int i = 1; i <= sqrt; i++) {
			if (number % i == 0) divisors += 2;
		}
		if (sqrt*sqrt == number) divisors--;
		return divisors;
	}
}