/* Problem 2: Even Fibonacci Numbers
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

import java.io.*;
import java.util.*;

public class Problem2 {
	public static void main(String args[]) {
		long startTime = System.currentTimeMillis();

		double minus1 = 2;
		double current = 3;
		double sum = 2;
		double temp;

		while (current <= 4000000) {
			temp = current;
			current += minus1;
			if (current % 2 == 0) sum += current;
			minus1 = temp;
		}

		System.out.println(sum);

		long endTime = System.currentTimeMillis();
		long totalTime = endTime - startTime;
		System.out.println("Total run time was " + totalTime + " milliseconds.");
	}
}